import Getters

def get_player_from_discord(name: str) -> str:
    match name:
        case "rainbowhead":
            return "AH"
        case "slane3470":
            return "I"
        case ".celari":
            return "N"
        case "dadude":
            return "S"
        case "draconic_lord":
            return "X"
        case "thereligionofpeanut":
            return "AC"
        case "orourkustortoise":
            return "AH"
        case "toomai1970":
            return "AM"
        case "lazymech.":
            return "AR"
        case "antinium1312.":
            return "AW"
        case "brotatornator666":
            return "BB"
        case "ianoid":
            return "BG"
        case "roobinski":
            return "BL"
        case "bossors":
            return "BQ"
        case "tsarplatinum":
            return "BV"
        case "ordainedtick266":
            return "CA"
        case "hamsternaut":
            return "CF"
        case ".defize":
            return "CK"
        case "._._neon_._.":
            return "CP"
        case "vandyss":
            return "CU"
        case "brob5046":
            return "CZ"
        case "benign_skies":
            return "DE"
        case "cgotnr":
            return "DJ"
        case "seventyseven_77":
            return "DO"
        case "trees17":
            return "DT"
        case "jetotavio":
            return "DY"
        case "livburrowss":
            return "ED"
        case "sincerenumber82":
            return "EI"
        case "withasideofsalt":
            return "EN"
        case "thorijus":
            return "ES"
        case "arcticreaper91":
            return "EX"
        case "theytookawaymyzalgo":
            return "FC"
        case "aero1908":
            return "FH"
        case _: #Error if not found player
            return "ERROR"

        
def find_player(player: str) -> chr:
    match player:
        case "total":
            return "D"
        case "oliver":
            return "I"
        case "sophie":
            return "N"
        case "ethan":
            return "S"
        case "richard":
            return "X"
        case "dan":
            return "AC"
        case "callum":
            return "AH"
        case "ryan":
            return "AM"
        case "stuart":
            return "AR" 
        case "ant":
            return "AW"
        case "antknee":
            return "AW"
        case "ronnie":
            return "BB"
        case "ian":
            return "BG"
        case "reuben":
            return "BL"
        case "findlay":
            return "BQ"
        case "daniel":
            return "BV"
        case "emily":
            return "CA"
        case "laurence":
            return "CF"
        case "benn":
            return "CK"
        case "bens":
            return "CP"
        case "andy":
            return "CU"
        case "ben3":
            return "CZ"
        case "carrick":
            return "DE"
        case "connor":
            return "DJ"
        case "drystan":
            return "DO"
        case "heather":
            return "DT"
        case "etienne":
            return "DY"
        case "liv":
            return "ED"
        case "rory":
            return "EI"
        case "scott":
            return "EN"
        case "tj":
            return "ES"
        case "lochlann":
            return "EX"
        case "colin":
            return "FC"
        case "aaron":
            return "FH"
        case "nonplayer":
            return "FR"
        case _: #Error if not found player
            return "ERROR"
        
def find_role(Role: str) -> int:
    match Role:
        #Townsfolk
        case "acrobat":
            return 5
        case "alchemist":
            return 6
        case "alsaahir":
            return 7
        case "amnesiac":
            return 8
        case "artist":
            return 9
        case "atheist":
            return 10
        case "balloonist":
            return 11
        case "banshee":
            return 12
        case "bounty hunter":
            return 13
        case "cannibal":
            return 14
        case "chambermaid":
            return 15
        case "chef":
            return 16
        case "choirboy":
            return 17
        case "clockmaker":
            return 18
        case "courtier":
            return 19
        case "cult Leader":
            return 20
        case "dreamer":
            return 21
        case "empath":
            return 22
        case "engineer":
            return 23
        case "exorcist":
            return 24
        case "farmer":
            return 25
        case "fisherman":
            return 26
        case "flowergirl":
            return 27
        case "fool":
            return 28
        case "fortune teller":
            return 29
        case "gambler":
            return 30
        case "general":
            return 31
        case "gossip":
            return 32
        case "grandmother":
            return 33
        case "high priestess":
            return 34
        case "huntsman":
            return 35
        case "innkeeper":
            return 36
        case "investigator":
            return 37
        case "juggler":
            return 38
        case "king":
            return 39
        case "knight":
            return 40
        case "librarian":
            return 41
        case "lycanthrope":
            return 42
        case "magician":
            return 43
        case "mathmetician":
            return 44
        case "mayor":
            return 45
        case "minstrel":
            return 46
        case "monk":
            return 47
        case "nightwatchman":
            return 48
        case "noble":
            return 49
        case "oracle":
            return 50
        case "pacifist":
            return 51
        case "philosopher":
            return 52
        case "pixie":
            return 53
        case "poppy grower":
            return 54
        case "preacher":
            return 55
        case "princess":
            return 56
        case "professor":
            return 57
        case "ravenkeeper":
            return 58
        case "sage":
            return 59
        case "sailor":
            return 60
        case "savant":
            return 61
        case "seamstress":
            return 62
        case "shugenja":
            return 63
        case "slayer":
            return 64
        case "snake Charmer":
            return 65
        case "soldier":
            return 66
        case "steward":
            return 67
        case "tea lady":
            return 68
        case "town crier":
            return 69
        case "undertaker":
            return 70
        case "village idiot":
            return 71
        case "virgin":
            return 72
        case "washerwoman":
            return 73
        case "homebrew townsfolk":
            return 74
        case "townsfolk":
            return Getters.get_townsfolk()
        #Outsiders
        case "barber":
            return 79
        case "butler":
            return 80
        case "damsel":
            return 81
        case "drunk":
            return 82
        case "golem":
            return 83
        case "goon":
            return 84
        case "hatter":
            return 85
        case "heretic":
            return 86
        case "hermit":
            return 87
        case "klutz":
            return 88
        case "lunatic":
            return 89
        case "moonchild":
            return 90
        case "mutant":
            return 91
        case "ogre":
            return 92
        case "plague doctor":
            return 93
        case "politician":
            return 94
        case "puzzlemaster":
            return 95
        case "recluse":
            return 96
        case "saint":
            return 97
        case "snitch":
            return 98
        case "sweetheart":
            return 99
        case "tinker":
            return 100
        case "zealot":
            return 101
        case "homebrew outsider":
            return 102
        case "outsider":
            return Getters.get_outsider()
        #Minions
        case "assassin":
            return 111
        case "baron":
            return 112
        case "boffin":
            return 113
        case "boomdandy":
            return 114
        case "cerenovus":
            return 115
        case "devil's advocate":
            return 116
        case "evil twin":
            return 117
        case "fearmonger":
            return 118
        case "goblin":
            return 119
        case "godfather":
            return 120
        case "harpy":
            return 121
        case "marionette":
            return 122
        case "mastermind":
            return 123
        case "mezepheles":
            return 124
        case "organ grinder":
            return 125
        case "pit-hag":
            return 126
        case "poisoner":
            return 127
        case "psychopath":
            return 128
        case "scarlet woman":
            return 129
        case "spy":
            return 130
        case "summoner":
            return 131
        case "vizier":
            return 132
        case "widow":
            return 133
        case "witch":
            return 134
        case "wizard":
            return 135
        case "wraith":
            return 136
        case "xaan":
            return 136
        case "homebrew minion":
            return 137
        case "minion":
            return Getters.get_minion()
        #Demons
        case "al-hadikhia":
            return 142
        case "fang gu":
            return 143
        case "imp":
            return 144
        case "kazali":
            return 145
        case "legion":
            return 146
        case "leviathan":
            return 147
        case "lil' monsta":
            return 148
        case "lleech":
            return 149
        case "lord of typhon":
            return 150
        case "no dashii":
            return 151
        case "ojo":
            return 152
        case "po":
            return 153
        case "pukka":
            return 154
        case "riot":
            return 155
        case "shabaloth":
            return 156
        case "vigormortis":
            return 157
        case "vortox":
            return 158
        case "yaggababble":
            return 159
        case "zombuul":
            return 160
        case "homebrew demon":
            return 161
        case "demon":
            return Getters.get_demon()
        #Totals
        case "total good":
            return Getters.get_average_good()
        case "total evil":
            return Getters.get_average_evil()
        case "total":
            return Getters.get_average_total()
        #Error case if not found
        case _:
            return 0